spring:
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/currconv
    username: postgres
    password: 123

currencyUrl: "http://www.cbr.ru/scripts/XML_daily.asp"

user:
  login: root
  password: 123
  role: USER